### ISSUE TITLE
Manage SSH keys for rsync backups

### ISSUE THREAD

**Issue by jabbors** [giner/ansible-role-barman#5]
When setting up rsync backups it would simply the Ansible manifests if the SSH keys could be managed with the same module.

Happy to wrap up a proposal PR if it would be an acceptable contribution.

**Comment by giner** [comment]
Why would you want rsync based backup?

**Comment by jabbors** [comment]
There are 2 reasons and both are due to the size of the database (>1TB)

1) `pg_basebackup` is single threaded so it takes a long time to perform a backup. In slower I/O and network setups it might not even be possible to complete a backup within 24 hours, assuming you take a nightly backup.

In our tests a 250G database took ~30 minutes to complete with streaming backup vs ~15 minutes with rsync and 4 jobs.  

2) It becomes expensive in terms of storage as you can't take advantage of deduplication.

**Comment by jabbors** [comment]
Something like this

```
barman_ssh_key:
  name: id_ed25519
  public: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI**************************************************ab
  private: <encrypted base64 encoded value>

barman_ssh_authorized_keys:
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI**************************************************cd
    state: present
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI**************************************************ef
    state: present
```

With two simple tasks 

```
- name: set authorized keys for barman user
  authorized_key:
    state: '{{ item.state }}'
    user: 'barman'
    key: '{{ item.key }}'
  with_items: '{{ barman_ssh_authorized_keys }}'

- name: configure private key for barman user
  copy:
    dest: '/var/lib/barman/.ssh/{{ barman_ssh_key.name }}'
    content: '{{ barman_ssh_key.private | b64decode }}'
    mode: 0600
    owner: barman
    group: barman
  when: barman_ssh_key.private is defined
```
